name: deskconn
base: core24
version: git
summary: Desktop management suite
description: |
  Desktop management suite

grade: stable
confinement: strict
compression: lzo

parts:
  deskconn:
    plugin: go
    source: .
    build-snaps:
      - go
    build-packages:
      - git

apps:
  deskconnctl:
    command: bin/deskconnctl
    plugs:
      - network

  deskconnd:
    command: bin/deskconnd
    daemon: simple
    daemon-scope: user
    restart-condition: always
    plugs:
      - network
      - network-bind
